WITH RECURSIVE GEN_TREE AS (
    SELECT ID, PARENT_ID, 1 AS GENERATION
    FROM ECOLI_DATA
    WHERE PARENT_ID IS NULL
    UNION ALL
    
    SELECT E.ID, E.PARENT_ID, G.GENERATION+1
    FROM ECOLI_DATA E
    JOIN GEN_TREE G ON E.PARENT_ID = G.ID
)

SELECT
    COUNT(G.ID) AS COUNT,
    G.GENERATION
FROM GEN_TREE G
LEFT JOIN ECOLI_DATA CHILD ON G.ID = CHILD.PARENT_ID
WHERE CHILD.ID IS NULL
GROUP BY G.GENERATION
ORDER BY G.GENERATION ASC;

