-- 코드를 입력하세요
-- 1단계: 0부터 23까지의 숫자를 가진 가상 테이블 생성
WITH RECURSIVE TIME_CITE AS (
    SELECT 0 AS HOUR
    UNION ALL
    SELECT HOUR +1 FROM TIME_CITE WHERE HOUR<23
)

-- 2단계: 가상 테이블을 기준으로 원본 데이터를 LEFT JOIN
SELECT 
    T.HOUR,
    COUNT(A.ANIMAL_ID) AS COUNT
FROM TIME_CITE AS T
LEFT JOIN ANIMAL_OUTS AS A ON T.HOUR = HOUR(DATETIME)
GROUP BY T.HOUR
ORDER BY T.HOUR ASC;
