SELECT 
    ITEM_ID,
    ITEM_NAME, 
    RARITY
FROM ITEM_INFO
WHERE ITEM_ID IN (
    -- 2. ITEM_TREE에서 PARENT_ITEM_ID가 RARE 아이템인 ITEM_ID 찾기
    SELECT ITEM_ID
    FROM ITEM_TREE
    WHERE PARENT_ITEM_ID IN (
        -- 1. ITEM_INFO에서 RARITY가 RARE인 ITEM_ID 찾기
        SELECT ITEM_ID
        FROM ITEM_INFO
        WHERE RARITY = 'RARE'
    )
)
ORDER BY ITEM_ID DESC;